#===========================================================#
# message code(error, info) definition                      #
#===========================================================#

# ERROR MESSAGE
E000001: 商品コード[%s]の商品は見つかりませんでした。
E000002: 商品コード[%s]の商品はすでに登録されてます。
E000003: ユーザ認証に失敗しました。正しいキーを入力してください。
E000004: URLが正しくありません。正しいURLにアクセスしてください。
E000005: 買ったものはありません。
E000006: 買いたいものはありません。
E000007: ブログパーツは利用できません。
E000008: このサイトではブログパーツの利用が許可されていません。
E000009: 商品コード[%s]の商品は登録できませんでした。

# INFOMATION MESSAGE
I000001: ユーザ【%s】が商品【%s】を登録しました。
I000002: ユーザ【%s】が商品【%s】を【買いたいものリスト】に登録しました。
I000003: %sの買ったもの
I000004: %sの買いたいもの